idf_component_register(
    SRCS
        "main.c"
        "auth.c"
        "storage.c"
        "wifi.c"
        "web_server.c"
        "ble_central.c"
        "ws_bridge.c"
        "status_led.c"
        "ota_update.c"
    INCLUDE_DIRS "."
    REQUIRES
        esp_http_server
        esp_wifi
        esp_netif
        esp_event
        esp_timer
        nvs_flash
        spiffs
        mbedtls
        json
        esp_driver_gpio
        app_update
        bt
)
